In [1]:
import numpy as np

notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [2]:
mon_array_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
## pour selectionner la valeur de la troisième colonne première ligne
print(mon_array_bidimensionnel[0,2])
print(mon_array_bidimensionnel[0,2])
## pour selectionner la première ligne
print(mon_array_bidimensionnel[:,0])
## pour selectionner la première colonne
print(mon_array_bidimensionnel[0,:])

3
3
[1 4 7]
[1 2 3]


In [4]:
mon_array_bidimensionnel[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [8]:
mon_array_bidimensionnel.dtype

dtype('int64')

In [9]:
mon_array_bidimensionnel = np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float64')

In [13]:
import numpy as np

mon_array_zeros = np.zeros((4,6))
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
import numpy as np

mon_array_ones = np.ones((4,6))
print(mon_array_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [15]:
import numpy as np

mon_array_random=np.random.random((4,2))
print(mon_array_random)

[[0.07312794 0.80776148]
 [0.98498516 0.07158532]
 [0.83673237 0.1669508 ]
 [0.34711806 0.42431728]]


In [5]:
ls

iris_2.csv  iris.csv  numpy_pt1.ipynb


In [149]:
import numpy as np
iris = np.genfromtxt("iris.csv", delimiter = ";", skip_header=True, encoding='latin-1')
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [7]:
import numpy as np
np.savetxt("iris_2.csv",iris, delimiter=";")

In [8]:
print(iris[2,1])
print(iris[0,0])
print(iris[0,1])
print(iris[0,2])

3.2
5.1
3.5
1.4


In [9]:
iris[2,1]=4
print(iris[2,1])

4.0


In [10]:
iris[2,1]=3.2
print(iris[2,1])

3.2


In [11]:
iris[iris>2]

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [12]:
iris[iris>2].shape

(472,)

In [16]:
iris[iris>2].shape[0]

472

In [17]:
iris > 2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [22]:
iris[iris[:,1]>3]

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [4.9, 3

In [27]:
colonne = iris[iris[:,4]==3]
colonne[:,4]

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [32]:
notre_tableau= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Conetenu de notre_tableau :")
print(notre_tableau)
print("Nouveau tableau après fancy indexing :")
indice = np.array([[4,10,5],[12,8,9]])
A = notre_tableau[indice]
print(A)
print(A[0,2])

Conetenu de notre_tableau :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nouveau tableau après fancy indexing :
[[ 5 11  6]
 [13  9 10]]
6


In [33]:
notre_tableau[:3]

array([1, 2, 3])

In [34]:
notre_tableau[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
notre_tableau[3:7]

array([4, 5, 6, 7])

In [36]:
notre_tableau[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
notre_tableau[3:8:3]

array([4, 7])

In [41]:
notre_tableau[2::2]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [43]:
iris[145:,2:]

array([[5.2, 2.3, 3. ],
       [5. , 1.9, 3. ],
       [5.2, 2. , 3. ],
       [5.4, 2.3, 3. ],
       [5.1, 1.8, 3. ]])

In [44]:
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [45]:
iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [46]:
iris[-1,:]

array([5.9, 3. , 5.1, 1.8, 3. ])

In [47]:
sous_tableau = notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [48]:
sous_tableau[0] = 10
sous_tableau

array([10,  2,  3,  4,  5])

In [49]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
notre_tableau= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

sous_tableau = notre_tableau[:5].copy()
sous_tableau[0] = 10
print(sous_tableau)
print(notre_tableau)

[10  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [52]:
mon_tableau = np.array([[10,11,12],[13,14,15],[16,17,18]])
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [53]:
np.add(mon_tableau,10)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [58]:
A = np.multiply(mon_tableau,20)
print(A)
print(mon_tableau)

[[200 220 240]
 [260 280 300]
 [320 340 360]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [60]:
mon_tableau_2 = np.array([10,20,30])
print(mon_tableau_2)
print(mon_tableau)

[10 20 30]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [61]:
np.subtract(mon_tableau,mon_tableau_2)

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [63]:
mon_tableau_2

array([10, 20, 30])

In [64]:
mon_tableau_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mon_tableau_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
np.multiply(mon_tableau,mon_tableau_3)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [66]:
print("Somme sur l'ensemble des éléments :")
print(np.sum(iris, axis=0))
print("somme par ligne: ")
print(np.sum(iris, axis=1))

Somme sur l'ensemble des éléments :
[876.5 458.6 563.7 179.9 300. ]
somme par ligne: 
[11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [68]:
print(np.mean(iris, axis=0))
print(np.std(iris, axis=0))

[5.84333333 3.05733333 3.758      1.19933333 2.        ]
[0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]


In [70]:
print(np.max(iris, axis=0))

[7.9 4.4 6.9 2.5 3. ]


In [74]:
print(np.max(iris,axis=1))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [88]:
colonne_1 = iris[iris[:,4]==1]
colonne_2 = iris[iris[:,4]==2]
colonne_3 = iris[iris[:,4]==3]

print(np.mean(colonne_1,axis=0))
print(np.mean(colonne_2,axis=0))
print(np.mean(colonne_3,axis=0))

[5.006 3.428 1.462 0.246 1.   ]
[5.936 2.77  4.26  1.326 2.   ]
[6.588 2.974 5.552 2.026 3.   ]


In [92]:
print("Attribut size")
print(iris.size)
print("Attribut shape")
print(iris.shape)
print("Attribut dtype")
print(iris.dtype)
print("Attribut ndim")
print(iris.ndim)

Attribut size
750
Attribut shape
(150, 5)
Attribut dtype
float64
Attribut ndim
2


In [93]:
iris.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [94]:
print(iris[(iris[:,4] == 3) & (iris[:, 3] > 2)])

[[6.3 3.3 6.  2.5 3. ]
 [7.1 3.  5.9 2.1 3. ]
 [6.5 3.  5.8 2.2 3. ]
 [7.6 3.  6.6 2.1 3. ]
 [7.2 3.6 6.1 2.5 3. ]
 [6.8 3.  5.5 2.1 3. ]
 [5.8 2.8 5.1 2.4 3. ]
 [6.4 3.2 5.3 2.3 3. ]
 [7.7 3.8 6.7 2.2 3. ]
 [7.7 2.6 6.9 2.3 3. ]
 [6.9 3.2 5.7 2.3 3. ]
 [6.7 3.3 5.7 2.1 3. ]
 [6.4 2.8 5.6 2.1 3. ]
 [6.4 2.8 5.6 2.2 3. ]
 [7.7 3.  6.1 2.3 3. ]
 [6.3 3.4 5.6 2.4 3. ]
 [6.9 3.1 5.4 2.1 3. ]
 [6.7 3.1 5.6 2.4 3. ]
 [6.9 3.1 5.1 2.3 3. ]
 [6.8 3.2 5.9 2.3 3. ]
 [6.7 3.3 5.7 2.5 3. ]
 [6.7 3.  5.2 2.3 3. ]
 [6.2 3.4 5.4 2.3 3. ]]


In [96]:
np.append(notre_tableau,[21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [97]:
np.append(iris,[[10,10,10,10,10]],axis=0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,  0.2,  1. ],
       [ 5. ,  3. ,  1.6,

In [98]:
np.insert(notre_tableau,1,42)

array([ 1, 42,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [99]:
np.insert(notre_tableau, 1, [42,43,44,45,46])

array([ 1, 42, 43, 44, 45, 46,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20])

In [100]:
np.insert(iris, 1, [10,10,10,10,10], axis = 0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. , 10. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,

In [101]:
np.delete(iris, 1, axis = 1)

array([[5.1, 1.4, 0.2, 1. ],
       [4.9, 1.4, 0.2, 1. ],
       [4.7, 1.3, 0.2, 1. ],
       [4.6, 1.5, 0.2, 1. ],
       [5. , 1.4, 0.2, 1. ],
       [5.4, 1.7, 0.4, 1. ],
       [4.6, 1.4, 0.3, 1. ],
       [5. , 1.5, 0.2, 1. ],
       [4.4, 1.4, 0.2, 1. ],
       [4.9, 1.5, 0.1, 1. ],
       [5.4, 1.5, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [4.8, 1.4, 0.1, 1. ],
       [4.3, 1.1, 0.1, 1. ],
       [5.8, 1.2, 0.2, 1. ],
       [5.7, 1.5, 0.4, 1. ],
       [5.4, 1.3, 0.4, 1. ],
       [5.1, 1.4, 0.3, 1. ],
       [5.7, 1.7, 0.3, 1. ],
       [5.1, 1.5, 0.3, 1. ],
       [5.4, 1.7, 0.2, 1. ],
       [5.1, 1.5, 0.4, 1. ],
       [4.6, 1. , 0.2, 1. ],
       [5.1, 1.7, 0.5, 1. ],
       [4.8, 1.9, 0.2, 1. ],
       [5. , 1.6, 0.2, 1. ],
       [5. , 1.6, 0.4, 1. ],
       [5.2, 1.5, 0.2, 1. ],
       [5.2, 1.4, 0.2, 1. ],
       [4.7, 1.6, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [5.4, 1.5, 0.4, 1. ],
       [5.2, 1.5, 0.1, 1. ],
       [5.5, 1.4, 0.2, 1. ],
       [4.9, 1

In [102]:
np.delete(iris, [1,2,3,4], axis=0)

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4

In [103]:
np.delete(notre_tableau,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [104]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [107]:
notre_tableau_1, notre_tableau_2, notre_tableau_3,notre_tableau_4 = np.split(notre_tableau, [2,6,18])
print(notre_tableau_1, notre_tableau_2, notre_tableau_3,notre_tableau_4)

[1 2] [3 4 5 6] [ 7  8  9 10 11 12 13 14 15 16 17 18] [19 20]


In [109]:
array=np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("avant division")
print(array)
array1, array2 = np.vsplit(array, [2])
print("Après division")
print("array1: ",array1)
print("array2: ",array2)

avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
array1:  [[ 2.  5.  6.]
 [ 9. 10. 11.]]
array2:  [[5. 6. 9.]]


In [112]:
array=np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("avant division")
print(array)
array1, array2 = np.hsplit(array, [2])
print("Après division")
print("array1: ",array1)
print("array2: ",array2)

avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
array1:  [[ 2.  5.]
 [ 9. 10.]
 [ 5.  6.]]
array2:  [[ 6.]
 [11.]
 [ 9.]]


In [113]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9])
array3 = np.array([6,7,8,9])
print(array1)
print(array2)
np.concatenate([array1,array2,array3])

[1 2 3 4 5]
[6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9])

In [115]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = "float")
array2 = np.array([[2,5,6],[9,10,11],[5,6,9]], dtype = "float")
print("array1 :",array1)
print("array2 :",array2)
np.concatenate([array1,array2])

array1 : [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
array2 : [[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.]])

In [116]:
array3 = np.array([[4,10,13],[7,14,15]],dtype="float")
np.concatenate([array1,array2,array3])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.],
       [ 4., 10., 13.],
       [ 7., 14., 15.]])

In [118]:
array1 = np.array([15,16,47])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
print(array1)
print(5*"-")
print(array2)
print(5*"-")
print(np.vstack([array1,array2]))
array1 = np.array([[15],[16],[47]])
print(5*"-")

[15 16 47]
-----
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
-----
[[15. 16. 47.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
-----


In [119]:
print(array1)
print(5*"-")
print(array2)
print(5*"-")
print(np.hstack([array1,array2]))

[[15]
 [16]
 [47]]
-----
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
-----
[[15.  1.  2.  3.]
 [16.  4.  5.  6.]
 [47.  7.  8.  9.]]


In [120]:
## multiplication de deux tableaux ndarrays
array2*array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [121]:
# produit matriciel entre les deux matrices array2
np.mat(array2)*np.mat(array2)

matrix([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [158]:
iris2 = np.delete(iris,4,axis = 1)
moyenne = np.mean(iris2, axis=1)

iris3 = np.insert(iris, 5 , moyenne, axis = 1)
print(iris3)

[[5.1   3.5   1.4   0.2   1.    2.55 ]
 [4.9   3.    1.4   0.2   1.    2.375]
 [4.7   3.2   1.3   0.2   1.    2.35 ]
 [4.6   3.1   1.5   0.2   1.    2.35 ]
 [5.    3.6   1.4   0.2   1.    2.55 ]
 [5.4   3.9   1.7   0.4   1.    2.85 ]
 [4.6   3.4   1.4   0.3   1.    2.425]
 [5.    3.4   1.5   0.2   1.    2.525]
 [4.4   2.9   1.4   0.2   1.    2.225]
 [4.9   3.1   1.5   0.1   1.    2.4  ]
 [5.4   3.7   1.5   0.2   1.    2.7  ]
 [4.8   3.4   1.6   0.2   1.    2.5  ]
 [4.8   3.    1.4   0.1   1.    2.325]
 [4.3   3.    1.1   0.1   1.    2.125]
 [5.8   4.    1.2   0.2   1.    2.8  ]
 [5.7   4.4   1.5   0.4   1.    3.   ]
 [5.4   3.9   1.3   0.4   1.    2.75 ]
 [5.1   3.5   1.4   0.3   1.    2.575]
 [5.7   3.8   1.7   0.3   1.    2.875]
 [5.1   3.8   1.5   0.3   1.    2.675]
 [5.4   3.4   1.7   0.2   1.    2.675]
 [5.1   3.7   1.5   0.4   1.    2.675]
 [4.6   3.6   1.    0.2   1.    2.35 ]
 [5.1   3.3   1.7   0.5   1.    2.65 ]
 [4.8   3.4   1.9   0.2   1.    2.575]
 [5.    3.    1.6   0.2  

In [161]:
iris_mean = np.mean(iris[:,:4], axis=1)
iris_mean
print(np.insert(iris, 5,iris_mean, axis=1))

[[5.1   3.5   1.4   0.2   1.    2.55 ]
 [4.9   3.    1.4   0.2   1.    2.375]
 [4.7   3.2   1.3   0.2   1.    2.35 ]
 [4.6   3.1   1.5   0.2   1.    2.35 ]
 [5.    3.6   1.4   0.2   1.    2.55 ]
 [5.4   3.9   1.7   0.4   1.    2.85 ]
 [4.6   3.4   1.4   0.3   1.    2.425]
 [5.    3.4   1.5   0.2   1.    2.525]
 [4.4   2.9   1.4   0.2   1.    2.225]
 [4.9   3.1   1.5   0.1   1.    2.4  ]
 [5.4   3.7   1.5   0.2   1.    2.7  ]
 [4.8   3.4   1.6   0.2   1.    2.5  ]
 [4.8   3.    1.4   0.1   1.    2.325]
 [4.3   3.    1.1   0.1   1.    2.125]
 [5.8   4.    1.2   0.2   1.    2.8  ]
 [5.7   4.4   1.5   0.4   1.    3.   ]
 [5.4   3.9   1.3   0.4   1.    2.75 ]
 [5.1   3.5   1.4   0.3   1.    2.575]
 [5.7   3.8   1.7   0.3   1.    2.875]
 [5.1   3.8   1.5   0.3   1.    2.675]
 [5.4   3.4   1.7   0.2   1.    2.675]
 [5.1   3.7   1.5   0.4   1.    2.675]
 [4.6   3.6   1.    0.2   1.    2.35 ]
 [5.1   3.3   1.7   0.5   1.    2.65 ]
 [4.8   3.4   1.9   0.2   1.    2.575]
 [5.    3.    1.6   0.2  

In [182]:
iris_column_mean = np.mean(iris, axis = 0)
print(np.insert(iris,iris.shape[0], iris_column_mean, axis=0))

[[5.1        3.5        1.4        0.2        1.        ]
 [4.9        3.         1.4        0.2        1.        ]
 [4.7        3.2        1.3        0.2        1.        ]
 [4.6        3.1        1.5        0.2        1.        ]
 [5.         3.6        1.4        0.2        1.        ]
 [5.4        3.9        1.7        0.4        1.        ]
 [4.6        3.4        1.4        0.3        1.        ]
 [5.         3.4        1.5        0.2        1.        ]
 [4.4        2.9        1.4        0.2        1.        ]
 [4.9        3.1        1.5        0.1        1.        ]
 [5.4        3.7        1.5        0.2        1.        ]
 [4.8        3.4        1.6        0.2        1.        ]
 [4.8        3.         1.4        0.1        1.        ]
 [4.3        3.         1.1        0.1        1.        ]
 [5.8        4.         1.2        0.2        1.        ]
 [5.7        4.4        1.5        0.4        1.        ]
 [5.4        3.9        1.3        0.4        1.        ]
 [5.1        3